import { shuffle } from "../../shared/shared";

export const incorrectMessages = shuffle([
  "Incorrect",
  "Incorrecto",
  "Falsch",
  "Erroné",
  "間違い",
  "错误",
  "잘못된",
  "Неправильно",
  "Fout",
  "Yanlış",
  "غلط",
  "गलत",
  "Λάθος",
  "Errato",
  "Feil",
  "Błędny",
  "Errado",
  "ผิด",
  "Sai",
  "Faux",
  "Verkeerd",
  "Неверно",
  "Väärä",
  "Incorrect",
  "Hatalı",
  "Không",
  "Nieprawidłowy",
  "Forkert",
  "Fel",
  "Eksik",
  "Rangt",
  "Galat",
  "Napačno",
  "არასწორი",
  "Неточно",
  "Kļūdains",
  "Neteisingai",
  "ខុស",
  "ຜິດພາດ",
  "मिथ्या",
  "തെറ്റായ",
  "Хибно",
  "မှားနေ",
  "चुकीचे",
  "ଭୁଲ",
  "අනිවාර්යයෙන්ම",
  "Хато",
  "తప్పు",
  "ผิดพลาด",
  "Yanlış",
  "Неправильний",
  "غلط",
]);

interface DefaultPlaylist {
  name: string;
  id: string;
}

export const defaultPlaylists: DefaultPlaylist[] = [
  { name: "Top 50 - USA", id: "37i9dQZEVXbLRQDuF5jeBp" },
  { name: "RapCaviar", id: "37i9dQZF1DX0XUsuxWHRQd" },
  { name: "Today's Top Hits", id: "37i9dQZF1DXcBWIGoYBM5M" },
  { name: "Billboard Hot 100", id: "6UeSakyzhiEt4NB3UAd6NQ" },
  { name: "Billboard #1s 2000 - Today", id: "5sUksHiPlavLs0dnDqvFgJ" },
  { name: "Every Billboard #1", id: "6eXlxttw7urdPUDEavpT17" },
  { name: "Classic Rock", id: "4cVibuAVfrfiwwZaHGpBzd" },
  { name: "All Time Rap Hits", id: "7GjUYpEYbpQ6lMiGxLVCJQ" },
  { name: "Billions Club", id: "37i9dQZF1DX7iB3RCnBnN4" },
].sort((a, b) => a.name.localeCompare(b.name));
